version: '3'

services:
  app:
    image: python:3.11
    platform: linux/amd64
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    working_dir: /demo-code
    volumes:
      - ./demo-code:/demo-code