[tool.ruff]
select = ["E", "F", "I", "UP"]
target-version = "py311"
line-length = 120
src = ["demo-code"]

[tool.black]
target-version =  ["py311"]
line-length = 120
extend-exclude = '''
(
  ^/demo-code/relecloud/migrations\/
)
'''
force-exclude = '''
# Needed for pre-commit
(
  ^/demo-code/relecloud/migrations\/
)
'''

[tool.pytest.ini_options]
addopts = "-ra --cov=backend"
pythonpath = [
  "demo-code"
]